version: '2'
services:
  apache:
    build: .
    image: zilleem-wb:latest
    volumes:
      - $PWD/html:/var/www/html
    ports:
      - "80:80"
    links:
      - db
      - redis
  db:
    image: mysql
    volumes:
      - $PWD/mysql/:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
    command: mysqld --max_allowed_packet=100M
  redis:
    image: redis:2.8
    ports:
      - "6379"
